apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: nginx
        test5: fuga2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          httpGet:
            path: /
            port: 80
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          httpGet:
            path: /
            port: 80
